spring.application.name=backend

spring.data.mongodb.database=${MONGODB_DATABASE:Smart_Campus}
spring.mongodb.embedded.version=7.0.11

server.port=8081

#  SERVE UPLOADED IMAGES
spring.web.resources.static-locations=file:./uploads/