spring.application.name=backend

server.port=8091

spring.data.mongodb.uri=mongodb+srv://admin:h1vG6BK4PpmeQbEl@cluster0.1hh0nlu.mongodb.net/Smart_Campus?retryWrites=true&w=majority

spring.web.resources.static-locations=file:./uploads/